version: '3'
services:
  webapp:
    build: ./src/SchoDotCom.WebUI
    image: scho-dot-com
  server:
    build: ./src/SchoDotCom.Server
    image: scho-dot-com-server
    ports:
      - "80:80"
      - "443:443"
    links:
      - webapp